### ISSUE TITLE
RAISE ASSERTION ERROR! nnUNet_predict 

### ISSUE THREAD

**Issue by dominiklangner23** [MIC-DKFZ/nnUNet#1379]
Hello Fabian,

I used the command nnUNetv2_find_best_configuration recommend for inference and get the following error:

(deeplearning) ubuntu@nnunetv2:/home/nnUNetV2_env$ nnUNetv2_predict -d Dataset501_Train_nnUnet -i /home/data/nnUNet_raw/Dataset501_Train_nnUnet/imagesTs/ -o /home/data/nnUNet_raw/Dataset501_Train_nnUnet/inferTs/ -f  0 1 2 3 4 -tr nnUNetTrainer -c 3d_fullres -p nnUNetPlans

Traceback (most recent call last):
  File "/home/nnUNetV2_env/miniconda3/envs/deeplearning/bin/nnUNetv2_predict", line 5, in <module>
    from nnunetv2.inference.predict_from_raw_data import predict_entry_point
  File "/home/nnUNetV2_env/miniconda3/envs/deeplearning/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 171
    RAISE ASSERTION ERROR!
          ^
SyntaxError: invalid syntax

Maybe you could tell me what I am doing wrong. Thanks in advance.

**Comment by FabianIsensee** [comment]
Fixed, sorry :-)

**Comment by Trista1105** [comment]
Hello, Fabian

I just tried nnUNetv2_predict, the above mentioned issue still exists.
The details are shown below. How can I solve this issue?
---------------------------------------------------
(nnunet) [xxxxx ~]$ nnUNetv2_predict -h
Traceback (most recent call last):
  File "/xxxxx/anaconda3/envs/nnunet/bin/nnUNetv2_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_predict')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxx/anaconda3/envs/nnunet/bin/nnUNetv2_predict", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/xxxxx/anaconda3/envs/nnunet/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxx/anaconda3/envs/nnunet/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/xxxxx/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 171
    RAISE ASSERTION ERROR!
          ^^^^^^^^^
SyntaxError: invalid syntax
---------------------------------------------

**Comment by FabianIsensee** [comment]
Should be fixed if you pull the current master
