### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by Rebecca3996** [MIC-DKFZ/nnUNet#172]
Hi,
I have started training using the following command:
 `python run/run_training.py 2d nnUNetTrainer Task00_Kidney 0 --ndet`.
 I get the following:
![Error1](https://user-images.githubusercontent.com/59051961/76611852-2c602700-6541-11ea-9389-ff837596d251.png) My question is why does it show 

> unable to plot network architecture

Do any of the files among **run_training.py, nnUNetTrainer.py, network_trainer.py** need to be configured?
and 

![Error2](https://user-images.githubusercontent.com/59051961/76612019-7c3eee00-6541-11ea-8d1c-b29bdb2501bb.png) 

The training is supposed to run for 1000 epochs but it got stopped at 129th epoch (as shown in the above image) and there is also no improvement in any of the loss functions. That is leading to a blank graph in **progress.png** files. That could be the reason for the following warning:

![Error3](https://user-images.githubusercontent.com/59051961/76612186-c45e1080-6541-11ea-9c92-307f83ed94e9.png)

Can anyone tell me what am I doing wrong? Pardon if this is a silly mistake since I am a beginner here.

**Comment by FabianIsensee** [comment]
Hi Rebecca,
The message about hiddenlayer  is not important. It is just a missing package that would allow you to see the generated network architecture if it was installed.
Your problem is that the loss is non for some reason. I don't know why that is - my guess is that there are nan values in your images. Please verify all the images with the following snippet:


```
import numpy as np
import SimpleITK as sitk
from batchgenerators.utilities.file_and_folder_operations import *


def check_image(img_fname: str):
    npy = sitk.GetArrayFromImage(sitk.ReadImage(img_fname))
    return np.any(np.isnan(npy))


def check_for_nan(input_folder: str):
    nii_files = subfiles(input_folder, suffix='.nii.gz')
    for n in nii_files:
        if check_image(n):
            print("nans found in ", n)
```

Run check_image on both your imagesTr and labelsTr folder!

Best,
Fabian

**Comment by Rebecca3996** [comment]
Hi, 
Thanks for your quick reply! I will surely look into what you have told.
Also, Is it possible that I might be getting the error due to the following configurations in the network_trainer.py file?
Eg:

 

> ################# SET THESE IN self.initialize() ###################################
>         self.network = None
>         self.optimizer = None
>         self.lr_scheduler = None
>         self.tr_gen = self.val_gen = None
>         self.was_initialized = False

I am not sure if I need to modify these?

**Comment by FabianIsensee** [comment]
You do not need to modify anything. It is all taken care of with nnU-Net

**Comment by Rebecca3996** [comment]
Okay. Thanks a lot! I am working on it.

**Comment by Rebecca3996** [comment]
Hi Fabian,
I have verified the images of the imagesTr and labelsTr by running `check_for_nan` and it runs without any error. `check_image` returns `False `as well.
![Error4](https://user-images.githubusercontent.com/59051961/76679922-837dfe80-660a-11ea-9fb7-a775f063109a.png)
If the code doesn't require any changes what could be the problem? 
I have also modified the kiTs dataset as per the instructions.

**Comment by FabianIsensee** [comment]
Hi,
please download one of the Decathlon datasets (Task04_Hippocampus is probably the best choice because it's the smallest) and try this one. If that does not give you nan's then the problem is definitely your dataset. There is not much I can do from here without seeing the data. 

nan's don't happen just like that. This is almost certainly not nnU-Net failing to cope with your dataset. You can also check the following:
- do you have multiple modalities? if so, is one of them sometimes empty (0 only)?
- have you made sure your labels are consecutive integers?

Best,
Fabian

**Comment by Rebecca3996** [comment]
Hello, 
I am sorry to reply  late. 
Yes the labels are consecutive integers. But I need to check the rest of the things as mentioned above. I experimented on Task04_Hippocampus data but only till dataset modification as per decathlon challenge and came directly to KiTs dataset to save me some time. I will work on it for sure.
(P.s: I am unable to access resources due to restrictions imposed to prevent corona).
Until then Thank you!

**Comment by FabianIsensee** [comment]
Hi, I just pushed an update. If you run preprocessing now you have the option to add --verify_dataset_integrity wich will check for the most common errors.
Best,
Fabian

**Comment by Rebecca3996** [comment]
Ok. That will make my task much easier. Thanks Fabian!

**Comment by FabianIsensee** [comment]
Have you had the chance to test it yet?

**Comment by Rebecca3996** [comment]
No I haven't had the chance yet. I will be able to test it by the end of this month probably. For now I am just looking through the ongoing issues. I am also eager to work on it asap. Thanks for bearing with me, Sir.

**Comment by Rebecca3996** [comment]
Hi Fabian
I want to execute the following command:
  `nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity`

But before that I executed this line:
 `nnUNet_convert_decathlon_task -i FOLDER_TO_TASK_AS_DOWNLOADED_FROM_MSD -p NUM_PROCESSES`  
where the FOLDER_TO_TASK_AS_DOWNLOADED_FROM_MSD is /mnt/komal/seema/**Task04_Hippocampus**

 I get the following error:
`AssertionError:` This does not seem to be a decathlon folder. Please give me a folder that starts with TaskXX and has the subfolders imagesTr, labelsTr and imagesTs`.
I have given the correct path and the folder contains the right subfolders. What is wrong here?

**Comment by Rebecca3996** [comment]
Hi Fabian
I want to execute the following command:
nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity

But before that I executed this line:
nnUNet_convert_decathlon_task -i FOLDER_TO_TASK_AS_DOWNLOADED_FROM_MSD -p NUM_PROCESSES
where the FOLDER_TO_TASK_AS_DOWNLOADED_FROM_MSD is /mnt/komal/seema/Task04_Hippocampus

I get the following error:
AssertionError: This does not seem to be a decathlon folder. Please give me a folder that starts with TaskXX and has the subfolders imagesTr, labelsTr and imagesTs`.
I have given the correct path and the folder contains the right subfolders. What is wrong here?

**Comment by FabianIsensee** [comment]
What is the output of
`ls /mnt/komal/seema/Task04_Hippocampus`?

**Comment by FabianIsensee** [comment]
ah and please try it with and without trailing /. I noticed some irregularities there that I will be fixing soon

**Comment by FabianIsensee** [comment]
I have fixed this issue now. If you pull from github it should work, as long as the input points to the correct folder

**Comment by Rebecca3996** [comment]
> What is the output of
> `ls /mnt/komal/seema/Task04_Hippocampus`?

It contains imagesTr, imagesTs, labelsTr and dataset.json

**Comment by Rebecca3996** [comment]
> I have fixed this issue now. If you pull from Github it should work, as long as the input points to the correct folder

Would you please elaborate on this? What do you mean by a pull from GitHub? I am sorry if this is something silly to ask

**Comment by Rebecca3996** [comment]
> ah and please try it with and without trailing /. I noticed some irregularities there that I will be fixing soon

The issue has been solved. There is no problem with the **Decathlon dataset: Task04_Hippocampus** now. It was just this **/** that I had to remove from the command:
 `nnUNet_convert_decathlon_task` -i /mnt/komal/seema/Task04_Hippocampus/ -p 8. 
I hope that it works on my dataset too. 
Dataset integrity verified too. Thank you! 

But I don't understand what does it mean by "If you pull from GitHub"?..Sorry if this is a silly question.

**Comment by FabianIsensee** [comment]
Hi,
you have installed nnunet with pip install? 
then run the following commands:

``` bash
pip uninstall nnunet
git clone https://github.com/MIC-DKFZ/nnUNet.git
cd nnunet
pip install -e .
cd
```

Then retry if it works :-)

Best,
Fabian

**Comment by Rebecca3996** [comment]
> Hi,
> you have installed nnunet with pip install?
> then run the following commands:
> 
> ```shell
> pip uninstall nnunet
> git clone https://github.com/MIC-DKFZ/nnUNet.git
> cd nnunet
> pip install -e .
> cd
> ```
> 
> Then retry if it works :-)
> 
> Best,
> Fabian

Oh okay. Got it!..But the issue has been already fixed. Do you think there might be any other issue that would rise if I don't execute the above commands and retry it? Because you said that you have fixed some irregularities.

**Comment by FabianIsensee** [comment]
I fixed it on the github code. For these changes to apply to you you need to reinstall the newest version which right now you can only get by using the commands I posted above.

**Comment by Rebecca3996** [comment]
> I fixed it on the github code. For these changes to apply to you you need to reinstall the newest version which right now you can only get by using the commands I posted above.

Okay. Understood. Thanks a lot!

**Comment by FabianIsensee** [comment]
Have you been able to run everything?

I will make a new release soon-ish where these changes will be incorporated. Once that is done you can simply `pip install --upgrade nnunet`

**Comment by Rebecca3996** [comment]
No. Not everything. There are other errors like the pytorch version and cuda driver version mismatch (that occured when I went to the training part)that I just finished resolving. I also need to work upon my own dataset. I have not been able to work fast due to some issues.
That is why I closed this issue temporarily.

**Comment by FabianIsensee** [comment]
If you still have problems you can leave it open. I am happy to help out.

When installing torch with `pip install torch` it will use some default cuda version. You need to make sure that the cuda version of your graphics driver matches or exceeds that number. Which version your driver supports is listed in the top right corner when you type `nvidia-smi` into your terminal : `CUDA Version: 10.2` on my PC.

Resolving this will require you to either update the graphics driver or manually choose an appropriate pytorch version:
https://pytorch.org/get-started/locally/

select stable -> linux -> pip -> Python -> your cuda version

Best,
Fabian

**Comment by Rebecca3996** [comment]
Thank you so much!. I appreciate this a lot. I am on it.

**Comment by Rebecca3996** [comment]
> If you still have problems you can leave it open. I am happy to help out.
> 
> When installing torch with `pip install torch` it will use some default cuda version. You need to make sure that the cuda version of your graphics driver matches or exceeds that number. Which version your driver supports is listed in the top right corner when you type `nvidia-smi` into your terminal : `CUDA Version: 10.2` on my PC.
> 
> Resolving this will require you to either update the graphics driver or manually choose an appropriate pytorch version:
> https://pytorch.org/get-started/locally/
> 
> select stable -> linux -> pip -> Python -> your cuda version
> 
> Best,
> Fabian

I installed Pytorch using the above steps.
When I use` nvidia-smi `it gives CUDA version:**10.1** 
When I use python prompt and execute the below lines:

> import torch
print((torch.cuda.version))

It also gives **10.1** But, 

> cat /usr/local/cuda/version.txt 

is giving CUDA version: **10.0.130**. I suppose it should give **10.1.150** since CUDA 10.1. 
nvidia-smi gives DRIVER version as 418.40.04. I am still facing the apex installation problem.

**Comment by FabianIsensee** [comment]
Have you tried the python only apex installation? This does not require cuda at all.
Best,
Fabian

**Comment by Rebecca3996** [comment]
> Have you tried the python only apex installation? This does not require cuda at all.
> Best,
> Fabian

Yes, python only apex does get installed without error. But I  wanted to know about this issue...what was causing the problem. As far as I understand all the requirements are satisfied. So,..But no problem.

**Comment by FabianIsensee** [comment]
Doing a regular apex installation is not required to run nnU-Net and it is much harder depending on your background. If the python only installation works I would advise simply using that :-)

**Comment by Rebecca3996** [comment]
> Doing a regular apex installation is not required to run nnU-Net and it is much harder depending on your background. If the python only installation works I would advise simply using that :-)

OKAY!

**Comment by Rebecca3996** [comment]
While training using

> nnUNet_train 2d nnUNetTrainerV2 Task000_Kidney 0

**it gives train loss and validation loss as nan.** I ran the same for **Task05_prostate**, it works fine. 

So, I conclude that definitely there is a problem with my dataset. 
Just for your information, _my dataset is the kits19 challenge dataset._ 
I have verified it using --verify_dataset_integrity.  It works fine.
I have also checked for nan values, there are no nan values plus the modality is also single and the labels are consecutive integers too. What is going wrong then?

**Comment by FabianIsensee** [comment]
Hi,
have you tried this code?
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task040_KiTS.py

That is how I converted the data.
Best,
Fabian

**Comment by Rebecca3996** [comment]
Hi Fabian,
                 I got to the training on my dataset successfully. But it is taking too long for every epoch. I am using Multi-GPU training. I have two GPUs.
**GPU 0: Tesla P100-PCIE-16GB 
GPU 1: Tesla P100-PCIE-16GB** 

> epoch:  0
2020-05-03 21:17:03.876579: train loss : -0.0581
2020-05-03 21:22:10.982428: validation loss: -0.2892
2020-05-03 21:22:10.983312: Average global foreground Dice: [0.6790443937798044, 0.006752636636494134]
2020-05-03 21:22:10.983395: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2020-05-03 21:22:12.251631: lr: 0.009991
2020-05-03 21:22:12.251979: This epoch took 4794.193279 s

Also when I use `nvidia-smi`, it is not giving me the running process ids. I set gpus for training using CUDA_VISIBLE_DEVICES=0,1.` htop `gives me this:
![ 2020-05-04 11-17-31](https://user-images.githubusercontent.com/59051961/80939048-e7e26080-8df8-11ea-8c95-9f0113a15522.png)

I think it is not using GPU at all.Why?

**Comment by Rebecca3996** [comment]
Hello Fabian
Why have you included all the cases i.e. 300 in the training in Task040_KiTs.py to convert the dataset?
There are labels corresponding to only 210 cases, and the remaining 90 are test cases. 

And for training, if I have previously used multi-gpu training for certain no. of epochs, Can I use single gpu configuration training from the last checkpoint saved?

**Comment by wwq1204** [comment]
Hi Fabian,
I have started training using the following command: `nnUNet_train 3d_fullres nnUNetTrainerV2 Task101_Kits19 0`
And I encountered the same problem as Rebecca when training the kits19 dataset.  The warning and error are shown in the following : 
<img width="901" alt="1589876364(1)" src="https://user-images.githubusercontent.com/26619886/82303013-f762cb80-99ec-11ea-87f5-006c41ae3e36.png">
<img width="737" alt="微信图片_20200519162628" src="https://user-images.githubusercontent.com/26619886/82303345-693b1500-99ed-11ea-9626-31c064c3ac24.png">
I guess it is the problem of the kits19 dataset, I have checked the kits19 dataset  by running `check_for_nan` and it runs without any error. Then, I print the “.pny” format data in my folder“/home/datasets/KiTS19-dataset/Kits19-V2/nnUNet_preprocessed/Task101_Kits19/nnUNetData_plans_v2.1_stage1” after preprocessing, the output is as following：
<img width="318" alt="1589877436(1)" src="https://user-images.githubusercontent.com/26619886/82304445-e915af00-99ee-11ea-8157-902e1011889e.png">
I think this is the reason why the program has the warning and loss=nan, how can I solve it?
Thank you!

**Comment by Rebecca3996** [comment]
Hii wwq1204,
I guess the problem occurs while converting the KiTs19 dataset in the required format. Even if I thought that I converted the dataset successfully somehow I ended up the same error repeatedly. The issue has been addressed here:
https://github.com/MIC-DKFZ/nnUNet/issues/172#issuecomment-621145412

I simply run the `Task040_KiTs.py` file and corrected some errors with it. Solved the issue. Hope that helps!

**Comment by wwq1204** [comment]
Hi Rebecca,
I used the method you said, and run `Task040_KiTS.py` to convert the dataset, but still have the same error, do you have other solutions to this problem?

**Comment by Rebecca3996** [comment]
Hi,
I am not sure about what is the problem. 
1. What did you get after running `Task040_KiTs.py?` Did you get` imagesTr, imagesTs, labelsTr` folders with a` dataset.json `file? 
2. Have you verified dataset integrity using 
`nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity`. 
3. Have you tried any other dataset (any among MSD) and see if it works? I initially tried it on Task005_Prostate dataset. If it works fine then the problem is definitely with the dataset as said by Fabian.
