### ISSUE TITLE
Error when using DDP and deep_supervision=False

### ISSUE THREAD

**Issue by XwK-P** [MIC-DKFZ/nnUNet#2571]
Only last conv layer in seg_layers will be used when deep_supervision=False. However DDP expects there are no unused parameters in the model. **PyTorch version 2.5**

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. Thi
s error indicates that your module has parameters that were not used in producing loss.

**Comment by saikat-roy** [comment]
Hi @XwK-P, sorry about the late reply. Are you still having this issue?

**Comment by Karol-G** [comment]
Hey,

Is this issue still relevant? Otherwise, I will close it in 14 days.

Best,
Karol

**Comment by XwK-P** [comment]
The issue is relevant under nnunetv2 2.6.4 and torch 2.4.0.  
The issue can reproduced using `nnunetv2_train` with  `-tr nnUNetTrainerNoDeepSupervision -num_gpus 2` on any dataset.

**Comment by Karol-G** [comment]
Hey,

I checked the code path. On current master, this should already be fixed. nnUNetTrainerNoDeepSupervision sets enable_deep_supervision=False, initialize() passes that into build_network_architecture, and since PR #2462 get_network_from_plans() now correctly forwards that flag into the actual architecture constructor. The old code path that re-enabled deep supervision in on_train_start was also removed. So DDP should no longer see unused deep-supervision parameters here.

If you still reproduce this, you are likely on an older nnU-Net version from before that fix, or on a custom architecture/trainer that still creates auxiliary segmentation heads even when deep_supervision=False.

Best,
Karol

**Comment by XwK-P** [comment]
@Karol-G  Hi Karol, thanks for taking another look but I don't think this is fixed on master. PR #2462 only ensured deep_supervision=False is forwarded as a kwarg; it doesn't address the underlying cause.    
                                                                                                                                                                                                          
The actual issue is in `dynamic_network_architectures.building_blocks.unet_decoder.UNetDecoder`: `seg_layers` is always built for every decoder stage, regardless of the `deep_supervision` flag (there's even a comment explaining it's done so checkpoints stay loadable either way). When `deep_supervision=False`, forward only calls `self.seg_layers[-1]`; the remaining `seg_layers[0..N-2]` are registered parameters that never participate in the loss.                                                                                                                                                          
                                                                                                                                                                                                          
On a single GPU this is harmless. Under DDP setting, `nnUNetTrainer.initialize()` wraps the model with `DDP(..., device_ids=[self.local_rank])`, no `find_unused_parameters=True`, and the reducer fails on the first backward. 
                                                                                                                                                                                                          
Easiest fix, on the nnU-Net side:                                                                                                                                                                       
   
```
  self.network = DDP(                                                                                                                                                                                     
      self.network,                                             
      device_ids=[self.local_rank],
      find_unused_parameters=not self.enable_deep_supervision,
  )   
```                                                                                                                                                                                                    
   
Gating on `enable_deep_supervision` avoids the perf cost for the default trainer. The alternative would be to freeze/skip the unused `seg_layers` in UNetDecoder when `deep_supervision=False`, but that's an upstream change in dynamic_network_architectures.             
                                                                                                                                                                                                          
Reproducible on current master with `nnUNetTrainerNoDeepSupervision`. Happy to open a PR with the one-line fix if useful.

**Comment by Karol-G** [comment]
Hey,

It seems you are correct! Fabian (main nnU-Net author) checked and confirmed the issue. He will investigate it now and prepare a fix. This might take a couple days though. Thank you for finding this issue!

Best,
Karol

**Comment by Karol-G** [comment]
@FabianIsensee Did you resolve this issue yet?

**Comment by FabianIsensee** [comment]
Nope haven't gotten around to doing that yet
