### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by lxg15066629402** [MIC-DKFZ/nnUNet#53]
RESULTS_FOLDER was not in your environment variables, network_training_output_dir could not be determined. Please go to nnunet/paths.py and manually set network_training_output_dir. You can ignore this warning if you are using nnunet only as a toolkit and don't intend to run network trainings
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 238, in <module>
    if not use_splitted or not isdir(join(splitted_4d_output_dir, task)):
  File "/home/tx-deepocean/anaconda3/envs/pycharm/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by FabianIsensee** [comment]
Hi,
please read the readme:

> Set paths
nnU-Net needs to know where you will store raw data, want it to store preprocessed data and trained models. Have a look at the file paths.py and adapt it to your system.

Best,
Fabian

**Comment by lxg15066629402** [comment]
I follow the readme, add the folder, I don't know why, I put nnunet_preprocessed and RESULTS_FOLDER and base in the same path, there are subfiles nnUNet_raw under base, and there are data I want to train under nnUNet_raw subfile. Is it right?

**Comment by FabianIsensee** [comment]
splitted_4d_output_dir seems to be None. It is none if base is not configures correctly in paths.py. Please verify that base if configured properly.
Best,
Fabian

**Comment by FabianIsensee** [comment]
RESULTS_FOLDER must be an environment variable pointing to some folder. You can also change the corresponding line in paths.py to some folder

**Comment by lxg15066629402** [comment]
How is RESULTS_FOLDER an environment variable pointing to a folder? I am not very clear about this place, the other splitted_4d_output_dir file, because I am 3D data, does this still need to be built?

**Comment by FabianIsensee** [comment]
please have a look at paths.py I pushed some changes right now to github to make it clearer

**Comment by lxg15066629402** [comment]
thank you

**Comment by lxg15066629402** [comment]
Excuse me, I am bothering you again. I have reorganized it according to what you said. I still have problems. I am very distressed. Take time to look at it. Thank you.



Thank you !!




------------------ 原始邮件 ------------------
发件人: "Fabian Isensee"<notifications@github.com>; 
发送时间: 2019年8月29日(星期四) 晚上6:26
收件人: "MIC-DKFZ/nnUNet"<nnUNet@noreply.github.com>; 
抄送: "Jone"<it_lxg@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MIC-DKFZ/nnUNet] TypeError: expected str, bytes or os.PathLikeobject, not NoneType (#53)




please have a look at paths.py I pushed some changes right now to github to make it clearer

**Comment by lxg15066629402** [comment]
------------------ 原始邮件 ------------------
发件人: "Fabian Isensee"<notifications@github.com>; 
发送时间: 2019年8月29日(星期四) 晚上6:26
收件人: "MIC-DKFZ/nnUNet"<nnUNet@noreply.github.com>; 
抄送: "Jone"<it_lxg@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MIC-DKFZ/nnUNet] TypeError: expected str, bytes or os.PathLikeobject, not NoneType (#53)




please have a look at paths.py I pushed some changes right now to github to make it clearer

**Comment by FabianIsensee** [comment]
Hi,
I don't know what exactly your problem is. Can you please give an example and show the error message?
Best,
Fabian

**Comment by sandipan** [comment]
We can create the required environment variables with python too, the following worked for me:

* First create 3 folders e.g., 
   1. nnUNet_raw_data_base # replace this path with your custom path
   2. nnUNet_preprocessed # replace this path with your custom path
   3. nnUNet_trained_models # replace this path with your custom path
   
* From python execute the following code:

    import os
    os.environ['nnUNet_raw_data_base'] = "nnUNet_raw_data_base"  # your path to nnUNet_raw_data_base
    os.environ['nnUNet_preprocessed'] = "nnUNet_preprocessed"     # your path to nnUNet_preprocessed
    os.environ['RESULTS_FOLDER'] = "nnUNet_trained_models"         # your path to nnUNet_trained_models
