### ISSUE TITLE
Error when trying to run train

### ISSUE THREAD

**Issue by markus-webcom** [MIC-DKFZ/nnUNet#618]
When trying to train a 3d_fullres model with `nnUNet_train 3d_fullres` I get the following error:

```
nerV2.py", line 431, in run_training
    ret = super().run_training()
  File "/home/m_kone06/.local/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/m_kone06/.local/lib/python3.8/site-packages/nnunet/training/network_training/network_trainer.py", line 446, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/m_kone06/.local/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 250, in run_iteration
    self.amp_grad_scaler.scale(l).backward()
AttributeError: 'NoneType' object has no attribute 'scale'
```

The strange thing is that some days ago I could start training without any problems. But I had to restart training after my server went down. Since then I cannot train any more.
I did not change anything!

Do you have any idea what could cause the problem?
I would be really grateful.
Kind regards

**Comment by FabianIsensee** [comment]
Hi Markus, yes I have an idea and I thought I fixed this a while ago. Let me look into this and get back to you

**Comment by FabianIsensee** [comment]
Hi markus, this should be fixed in the current master. If you install nnU-Net from github then the error should go away

**Comment by markus-webcom** [comment]
Thanks for the answer.
I will try next week and tell you if it works.

**Comment by Renshaw26** [comment]
What was the change that you implemented, I am still getting the same error even after pulling from master.
